"""tmrvc-core: shared constants, mel computation, type definitions."""

from tmrvc_core.constants import (
    D_MODEL,
    D_SPEAKER,
    HOP_LENGTH,
    MEL_FMAX,
    MEL_FMIN,
    N_FFT,
    N_MELS,
    SAMPLE_RATE,
    WINDOW_LENGTH,
)
from tmrvc_core.device import get_device, pin_memory_for_device
from tmrvc_core.types import (
    ActingTextureLatent,
    ActingTextureMacro,
    BootstrapCacheEntry,
    CFG_PRESERVED_FIELDS,
    CFG_ZEROED_FIELDS,
    CFGMode,
    FeatureSet,
    IntentCompilerOutput,
    PacingControls,
    PointerState,
    SpeakerProfile,
    SupervisionTier,
    TrajectoryProvenance,
    TrajectoryRecord,
    TTSBatch,
    TTSFeatureSet,
    UCLMFeatureSet,
    UCLM_Batch,
    Utterance,
    VoiceStateSupervision,
)

__all__ = [
    "ActingTextureLatent",
    "ActingTextureMacro",
    "BootstrapCacheEntry",
    "CFG_PRESERVED_FIELDS",
    "CFG_ZEROED_FIELDS",
    "CFGMode",
    "D_MODEL",
    "D_SPEAKER",
    "FeatureSet",
    "HOP_LENGTH",
    "IntentCompilerOutput",
    "MEL_FMAX",
    "MEL_FMIN",
    "N_FFT",
    "N_MELS",
    "PacingControls",
    "PointerState",
    "SAMPLE_RATE",
    "SpeakerProfile",
    "SupervisionTier",
    "TrajectoryProvenance",
    "TrajectoryRecord",
    "TTSBatch",
    "TTSFeatureSet",
    "UCLMFeatureSet",
    "UCLM_Batch",
    "Utterance",
    "VoiceStateSupervision",
    "WINDOW_LENGTH",
    "get_device",
    "pin_memory_for_device",
]
