cache_dir: data/cache
split: train
datasets:
  vctk:
    type: vctk
    enabled: true
    language: en
    raw_dir: data/raw/wav48_silence_trimmed
  jvs:
    type: jvs
    enabled: false
    language: ja
    raw_dir: data/raw/jvs_corpus
  tsukuyomi:
    type: tsukuyomi
    enabled: true
    language: ja
    raw_dir: "data/raw/tsukuyomi/corpus1/01 WAV（収録時の音量のまま）"
